---
title: "fastTestRun"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2005, 2010, 2015, 2020, 2030, 2040]
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
granularity: lowGran
regions: EUR
...
