---
title: "fastTestRun"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2005, 2010, 2015, 2020, 2030, 2040]
regions: DEU
# data
startingPoint: "output/small_2023-04-17_11.04.00/abort.gdx"
...
